Clean up config types
AccumulateNetwork/accumulate pull request #333
Opened 2021-12-09 22:27 UTC by firelizzard18

- Eliminate `RPC`
- Eliminate `API.RESTListenAddress`
- Rename `API.{JSON,}ListenAddress`
- Move website-related config into its own type
- Move network type, id into its own type
- Replace `Accumulated.Networks` and `.Directory` with
  `Network.BvnNames` and `.Addresses`
- Add helpers in config for changing the port number

And update everything touched by these changes.

2021-12-10 18:57 UTC, PaulSnow requested changes
Reviewed, but I don't have as much experience with this part of the code.
@bunfield Should review.

2021-12-10 23:53 UTC, bunfield approved these changes

2021-12-10 23:53 UTC, bunfield commented
Looks good to me.

2021-12-11 00:00 UTC, PaulSnow approved these changes

2021-12-11 00:00 UTC, merged