feat(sdk): migrated cli func to apiV2
AccumulateNetwork/accumulate pull request #345
Opened 2021-12-15 07:05 UTC by brohamgoham

2021-12-15 15:34 UTC, bunfield requested changes
instead of putting this in the libs directory, it should be under pkg (https://github.com/golang-standards/project-layout).  however, given this will require a lot more work, we should probably put it in internal/pkg until api is settled, at which time we can make it public.

I made comments to the first couple of files, but the comments carry throughout the code and apply to all files in this PR.

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +	Db             db.DB
The database should not be in sdk. key management is handled outside the sdk.

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +)
no bucket definitions should be here

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +func CreateAccount(url string, args []string) (string, error) {
the arguments passed to this function should not be an array of strings.  should be either the data structure of explicit parameters

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +	if err != nil {
we will not always have access to the private key.  For example, when passing on to a hardware wallet for signing.  need a signing callback or something similar

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +	return ActionResponseFrom(&res).Print()
the printing is customized for the cli and should not be part of the sdk.

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +
this function doesn't belong in the sdk.

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +func CreateAccount(url string, args []string) (string, error) {
perhaps explore the use of a builder pattern instead.

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/goaccumulate.go
> +	anon, err := Db.GetBucket(BucketAnon)
does not belong...

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/key.go
> +
key management should be handled by the wallet not the sdk.

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/page.go
> +	return PrintQueryResponseV2(&res)
the return needs to be basic type or just json. the print is custom to the cli

2021-12-15 15:34 UTC, bunfield commented on libs/goaccumulate/page.go
> +	return ar.Print()
see comments above about returning prints

2021-12-30 16:47 UTC, firelizzard18 commented
Moving to GitLab

2021-12-30 16:47 UTC, closed without merging